"""
Rule-based guardrails. Deliberately NOT LLM-based — safety gating should be
deterministic, not dependent on another model call that can itself fail/drift.
"""
import re
from typing import Tuple
from src.utils.config import get as cfg_get

MAX_OBJECTIVE_LENGTH = cfg_get("guardrails.max_objective_length", 500)

_INJECTION_PATTERNS = [
    r"ignore (all )?previous instructions",
    r"disregard (the )?system prompt",
    r"you are now",
    r"act as (an? )?unrestricted",
]

_PRESCRIBING_PATTERNS = [
    r"\bwhat dose (of|should)\b",
    r"\bhow many (mg|pills|tablets) should i\b",
    r"\bprescribe me\b",
]

CLINICAL_DISCLAIMER = (
    "This report is generated by an experimental AI research system for "
    "longitudinal case summarization. It is NOT a diagnosis and must not be "
    "used for clinical decision-making without review by a licensed clinician."
)


def check_objective(objective: str) -> Tuple[bool, str]:
    """
    Returns (ok, reason). ok=False means the request should be rejected
    before it ever reaches the LangGraph workflow.
    """
    if not objective or not objective.strip():
        return False, "Objective cannot be empty."

    if len(objective) > MAX_OBJECTIVE_LENGTH:
        return False, f"Objective exceeds {MAX_OBJECTIVE_LENGTH} characters."

    lowered = objective.lower()

    for pattern in _INJECTION_PATTERNS:
        if re.search(pattern, lowered):
            return False, "Objective appears to contain an instruction-override attempt."

    for pattern in _PRESCRIBING_PATTERNS:
        if re.search(pattern, lowered):
            return False, (
                "This system produces differential diagnoses from case data, not "
                "personal dosing/prescribing advice. Consult a clinician or pharmacist."
            )

    return True, ""


def append_disclaimer(report_text: str) -> str:
    if not cfg_get("guardrails.require_disclaimer", True):
        return report_text
    return f"{report_text}\n\n---\n{CLINICAL_DISCLAIMER}"